version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: laravel_db
        restart: always
        environment:
            POSTGRES_DB: starter-project
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: guga
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    node:
        image: node:20
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - "5173:5173"

volumes:
    db_data:
